# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :submit do
    ensure_git_status_clean
    increment_build_number
    build_app(workspace: "TennisLadder.xcworkspace", scheme: "TennisLadder")
    upload_to_testflight
    deliver(
      skip_binary_upload: true,
      skip_screenshots: true,
      submit_for_review: true,
      force: true,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
    commit_version_bump
    add_git_tag
    push_to_git_remote
  end
end
